network.host: 0.0.0.0
discovery.type: single-node
xpack.security.enabled: false #无需密码
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "*"
action.auto_create_index: true #禁止自动创建索引